ccsproject/ccsproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('job/', include("jobs.urls")),
    path('timetrack/', include("timetrack.urls")),
]

ccsproject/jobs/urls.py
from django.contrib import admin
from django.urls import include, path
from jobs.views import JobListView, JobCreateView, JobUpdateView, JobDeleteView

urlpatterns = [
    path('list/', JobListView.as_view(), name='job-list'),
    path('create/', JobCreateView.as_view(), name='job-create'),
    path('update/<pk>/', JobUpdateView.as_view(), name='job-update'),
    path('delete/<pk>/', JobDeleteView.as_view(), name='job-delete')
]

ccsproject/jobs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Job(models.Model):
    number_string = models.CharField(verbose_name="Job Number", max_length=140, blank=False, null=False)
    title = models.CharField(verbose_name="Title", max_length=250, blank=False, null=False)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now=True, blank=False, null=False)

    @property
    def class_name(self):
        return self.__class__.__name__

    def __str__(self):
        return self.number_string + ": " + self.title

ccsproject/timetrack/models.py
from django.db import models
from django.contrib.auth.models import User
from jobs.models import Job
from djmoney.models.fields import MoneyField
from ccsproject.settings import DEFAULT_MILEAGE_RATE
import datetime

# Create your models here.
class Timecodes(models.Model):
    number = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=140)

    @property
    def class_name(self):
        return self.__class__.__name__
    
    def __str__(self):
        return str(self.number) + ": " + str(self.description)

class Timesheet(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    start_date = models.DateField(verbose_name="Start Date", null=False, blank=False)
    end_date = models.DateField(verbose_name="End Date", null=False, blank=False)
    submitted = models.DateTimeField(verbose_name="Submitted", null=True, blank=True)

    @property
    def is_submitted(self):
        if self.submitted is not null:
            return True
        else:
            return False
        # end if
        
    @property
    def class_name(self):
        return self.__class__.__name__
    
    @property
    def has_children(self):
        if len(TimeEntry.objects.filter(sheet=self))==0 and len(Expense.objects.filter(sheet=self))==0:
            return False
        else:
            return True
        # end if
    
    def __str__(self):
        return "user: %s,    start: %s,    end: %s" % (self.user, self.start_date, self.end_date)


class TimeEntry(models.Model):
    sheet = models.ForeignKey(Timesheet, on_delete=models.CASCADE, null=False, blank=False)
    date = models.DateField(blank=False, null=False)
    job = models.ForeignKey(Job, on_delete=models.PROTECT, null=True, blank=True)
    code = models.ForeignKey(Timecodes, on_delete=models.DO_NOTHING, null=False, blank=False)
    hours = models.FloatField(default=0.0, null=False, blank=False)
    description = models.TextField(blank=True, null=True, default="")

    @property
    def class_name(self):
        return self.__class__.__name__
    
    def __str__(self):
        return str(self.date) + ", Job: " + str(self.job.number_string) + ", Code: " + str(self.code.number) + ", " + str(self.hours) + ",    Description: " + str(self.description)

class Expense(models.Model):
    sheet = models.ForeignKey(Timesheet, on_delete=models.CASCADE, null=False, blank=False)
    date = models.DateField(blank=False, null=False)
    job = models.ForeignKey(Job, verbose_name="Job", on_delete=models.PROTECT, null=True, blank=True)
    miles = models.FloatField(verbose_name="Miles", default=0, null=False, blank=False)
    mileage_rate = MoneyField(verbose_name="Mileage Rate", max_digits=3, decimal_places=2, default=DEFAULT_MILEAGE_RATE, default_currency="USD")
    air_fare = MoneyField(verbose_name="Air Fare", max_digits=7, decimal_places=2, default=0.0, default_currency="USD")
    hotel = MoneyField(verbose_name="Hotel", max_digits=5, decimal_places=2, default=0.0, blank=False, null=False, default_currency="USD")
    other = MoneyField(verbose_name="Other Expense", max_digits=5, decimal_places=2, default=0.0, blank=False, null=False, default_currency="USD")
    explanation = models.CharField(max_length=500, null=True, blank=True)

    @property
    def class_name(self):
        return self.__class__.__name__
    
    def __str__(self):
        return "expense " + str(self.date) + ", " + str(self.amount) + ", " + str(self.explanation)

ccsproject/templates/base.html
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
        <style>
            .ccs_orange{
                color: #F26521;
            }
            a{
                color: #F26521;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="the_navigator">
            <div class="container-fluid">
              <a class="navbar-brand ccs_orange" href="#">CCS Management</a>
              <button class="navbar-toggler ccs_orange" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                  <li class="nav-item">
                    <a class="nav-link ccs_orange" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link ccs_orange dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Jobs
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                      <li><a class="dropdown-item ccs_orange" href="{% url 'job-list' %}">List</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item ccs_orange" href="{% url 'job-create' %}">Create</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle ccs_orange" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Timetrack
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                      <li><a class="dropdown-item ccs_orange" href="#">Latest</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item ccs_orange" href="{% url 'sheet-list' %}">List</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item ccs_orange" href="{% url 'sheet-create' %}">Create</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        <div class="container">
            <div class='jumbotron'>
                <h1 class='display-4'>{{ title }}</h1>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

ccsproject/templates/confirm.html
{% extends "base.html" %}
{% block content %}
    <form method="post" class="card">
        {% csrf_token %}
        <h2>Delete {{ object.class_name }}</h2>
        <p>Are you sure you want to delete {{ object.class_name }} [ {{ object }} ]</p>
        <p>All child objects could also be deleted; this is not reversable.</p>
        <p class="form-buttons">
			<input type="submit" class="btn btn-primary" value="Delete">
			<a href="{{ request.GET.next }}" class="btn btn-outline">Cancel</a>
		</p>
    </form>
{% endblock %}

ccsproject/templates/form-view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    {% if view.get_classname == 'JobCreateView' %}
        <h1>Job Create</h1>
    {% elif view.get_classname == 'JobUpdateView' %}
        <h1>Job Update</h1>
    {% elif view.get_classname == 'TimesheetCreateView' %}
        <h1>Timesheet Create</h1>
    {% elif view.get_classname == 'TimesheetUpdateView' %}
        <h1>Timesheet Update</h1>
    {% else %}
        <h1>Form View</h1>
    {% endif %}

    {% crispy form %}
{% endblock %}

ccsproject/templates/list-view.html
{% extends "base.html" %}
{% block content %}
    {%if view.get_classname == 'JobListView' %}
        {% if job_list %}
            <table class='table'>
                <tr>
                    <th>Job</th>
                    <th>Title</th>
                    <th>Created By</th>
                    <th>Created</th>
                    <th></th>
                </tr>
                {% for job in job_list %}
                    <tr>
                        <td>{{ job.number_string }}</td>
                        <td>{{ job.title }}</td>
                        <td>{{ job.created_by }}</td>
                        <td>{{ job.created }}</td>
                        <td>
                            <a href="{% url 'job-update' pk=job.id %}?next={% url 'job-list' %}">
                                <i class="fs-5 bi bi-pencil-square"></i>
                            </a>
                            <a href="{% url 'job-delete' pk=job.id %}?next={% url 'job-list' %}">
                                <i class="p-2 fs-5 bi bi-trash-fill"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>No jobs yet.</p>
        {% endif %}

        <a href={% url 'job-create' %}?next={%url 'job-list' %}>Create a new job</a>
    
    <!-- Timesheet List View -->
    {% elif view.get_classname == 'TimesheetListView' %}
        {% if timesheet_list %}
            <table class='table'>
                <tr>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th></th>
                </tr>

                {% for timesheet in timesheet_list %}
                    <tr>
                        <td>{{ timesheet.start_date }}</td>
                        <td>{{ timesheet.end_date }}</td>
                        {% if not timesheet.has_children %}
                        <td>
                            <a href="{% url 'entry-list' timesheet.id %}">
                                <i class="p-2 fs-5 bi bi-binoculars-fill"></i>
                            </a>
                            <a href="{% url 'sheet-update' pk=timesheet.id %}?next={% url 'sheet-list' %}">
                                <i class="fs-5 bi bi-pencil-square"></i>
                            </a>
                            <a href="{% url 'sheet-delete' pk=timesheet.id %}?next={% url 'sheet-list' %}">
                                <i class="p-2 fs-5 bi bi-trash-fill"></i>
                            </a>
                        </td>
                        {% else %}
                        <td>
                            <a href="{% url 'entry-list' timesheet.id %}">
                                <i class="p-2 fs-5 bi bi-binoculars-fill"></i>
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>No timesheets for user yet.</p>
        {% endif %}
        <a href={% url 'sheet-create' %}?next={% url 'sheet-list' %}>Create a new timesheet</a>
    {% else %}
        <p>The big nothing.</p>
    {% endif %}

{% endblock %}